name: Workflow
on: 
  workflow_dispatch:
    inputs:
      goamd64:
        description: 'GOAMD64'
        required: false
        type: string
      exclude-services:
        description: 'exclude services'
        required: false
        type: string

jobs:
  test: # Job ID
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build Go
        uses: ./.github/actions/build-go-services
        with:
          goamd64: ${{ inputs.goamd64 }}
          exclude-services: ${{ inputs.exclude-services }}
      - name: Build docker images
        run: echo "Creating..."
  # create-image:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Image
  #       run: echo "Creating..."